Repository BenLorantfy/nestjs-zod, pull requests merged in 2023-04, with the labels that each got.

#29 Export validate function
  README.md
  src/index.ts
Labels: feature

#30 Fix openapi type check
  src/openapi/zod-to-openapi.ts
Labels: fix

#31 Fix openapi type check 2
  src/openapi/zod-to-openapi.ts
Labels: fix

#32 Fix openapi type check 3
  rollup.config.js
  src/openapi/zod-to-openapi.ts
Labels: fix

#37 Update pr-labeler
  .github/workflows/pr-labeler.yml
Labels: chore

#36 feat: upgrade to support zod 3.21.x
  package.json
  src/openapi/zod-to-openapi.ts
  src/z/issues/overrided.ts
  yarn.lock
Labels: feature

#22 Update README.md
  README.md
Labels: documentation, help wanted
