Repository BenLorantfy/nestjs-zod, pull requests merged in 2024-10, with the labels that each got.

#106 Fix release process and README tweaks
  .github/workflows/release.yml
  README.md
Labels: chore

#107 Use deepmerge instead of merge-deep
  README.md
  packages/nestjs-zod/package.json
  packages/nestjs-zod/src/openapi/zod-to-openapi.ts
  pnpm-lock.yaml
Labels: fix

#109 Update README.md openapi section for additional clarity
  README.md
Labels: documentation
